//组件化要解决的问题
1.统一管理项目开发环境
使用gradle.properties 配置项目编译环境属性，例如CompileSdkVersion等

2.组件需要满足单独运行与调试的要求

可以作为一个application单独运行与调试
3.实现组件之间界面跳转和数据传递
为组件创建中间接口，每个组件需要提供各自的实现

4.组件相互之间的集成调试，包括只依赖部分组件
在gradle.properties中配置组件是否独立运行属性，通过调整属性值为false进行集成调试

5.组件中application的使用
在app中通过反射实例化组件的Application对象

6.组件之间实现代码隔离，资源文件隔离
在app中使用runtimeOnly依赖组件实现代码隔离，此方法强制本moudle在编译时不能引用另外一个moudle
在组件中使用resourcePrefix '组建名'实现资源文件隔离